name: credentials_management
description: An app for storing passwords securely.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.1
  lint: ^1.5.3
  equatable: ^2.0.5
  flutter_secure_storage: ^5.0.2
  local_auth: ^2.1.0
  google_fonts: ^3.0.1
  hive: ^2.0.0
  flutter_slidable: ^2.0.0
  hive_flutter: ^1.0.0
  path_provider: ^2.0.1
  http: ^0.13.4
  google_sign_in: ^5.4.1
  firebase_core: ^1.22.0
  firebase_auth: ^3.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.0
  build_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
