// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4kpk2vMUBa-xO47n9la7ErmHJJkbXR_I',
    appId: '1:981134640599:android:a55118f771dc0e451eb792',
    messagingSenderId: '981134640599',
    projectId: 'credentials-0',
    storageBucket: 'credentials-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw-FUhX23v380IkSB04iNzCaRYHq73ZLs',
    appId: '1:981134640599:ios:6f1da7858c3067cc1eb792',
    messagingSenderId: '981134640599',
    projectId: 'credentials-0',
    storageBucket: 'credentials-0.appspot.com',
    androidClientId: '981134640599-qe64qfscbpkvigei476vhb1s2urhfk0d.apps.googleusercontent.com',
    iosClientId: '981134640599-sb4ipf1mduu11jof47mq258il43hdr8t.apps.googleusercontent.com',
    iosBundleId: 'com.addow.credentialsManagement',
  );
}
